# Site settings
title: WORKGARDEN
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://workgarden.de" # the base hostname & protocol for your site
author: Copyright &copy; 2020 - Conciso GmbH
lang: de_DE


# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll_picture_tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md

picture: 
  suppress_warnings: true

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-77801671-2       # Required - replace with your tracking id
    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking
